# Generated by Django 4.2 on 2023-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actedactivity',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
