# Generated by Django 4.2 on 2023-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_tag_actedactivity_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actedactivity',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='activities.tag'),
        ),
    ]
