# Generated by Django 4.2 on 2023-05-14 07:38

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
