# Generated by Django 4.2 on 2023-05-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_price_currency_alter_purchase_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-datetime', 'place']},
        ),
    ]
