# Generated by Django 4.2 on 2023-06-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_product_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-datetime', 'place']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('necessary', 'Necessary')], default='necessary', max_length=56),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place', to='expenses.place'),
        ),
    ]
