# Generated by Django 4.2 on 2023-05-14 09:08

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽')], default='RUB', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14)),
                ('datetime', models.DateTimeField(verbose_name='Income received')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomes.incomesource')),
            ],
        ),
    ]
