# Generated by Django 4.2 on 2023-05-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_income_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-datetime', 'source']},
        ),
    ]
